In [ ]:
import gradio as gr
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
from google.colab import files
files.upload()

In [ ]:
# Load data
# Load CSV files
data = pd.read_csv('athlete_events.csv')
regions = pd.read_csv('datasets_31029_40943_noc_regions.csv')

# Merge datasets
merged = pd.merge(data, regions, on='NOC', how='left')

# Display a few rows
print(merged.head())

   ID                      Name Sex   Age  Height  Weight            Team  \
0   1                 A Dijiang   M  24.0   180.0    80.0           China
1   2                  A Lamusi   M  23.0   170.0    60.0           China
2   3       Gunnar Nielsen Aaby   M  24.0     NaN     NaN         Denmark
3   4      Edgar Lindenau Aabye   M  34.0     NaN     NaN  Denmark/Sweden
4   5  Christine Jacoba Aaftink   F  21.0   185.0    82.0     Netherlands

   NOC        Games  Year  Season       City          Sport  \
0  CHN  1992 Summer  1992  Summer  Barcelona     Basketball
1  CHN  2012 Summer  2012  Summer     London           Judo
2  DEN  1920 Summer  1920  Summer  Antwerpen       Football
3  DEN  1900 Summer  1900  Summer      Paris     Tug-Of-War
4  NED  1988 Winter  1988  Winter    Calgary  Speed Skating

                              Event Medal       region notes
0       Basketball Men's Basketball   NaN        China   NaN
1      Judo Men's Extra-Lightweight   NaN        China   NaN
2           Football Men's Football   NaN      Denmark   NaN
3       Tug-Of-War Men's Tug-Of-War  Gold      Denmark   NaN
4  Speed Skating Women's 500 metres   NaN  Netherlands   NaN

In [ ]:
def gold_medal_age_distribution():
    gold = merged[merged['Medal'] == 'Gold']
    plt.figure(figsize=(10, 5))
    sns.histplot(gold['Age'].dropna(), bins=30, kde=True)
    plt.title('Age Distribution of Gold Medal Winners')
    plt.xlabel('Age')
    plt.ylabel('Number of Athletes')
    plt.tight_layout()
    return plt.gcf()

In [ ]:
def female_participation():
    women = merged[(merged['Sex'] == 'F') & (merged['Season'] == 'Summer')]
    plt.figure(figsize=(12, 6))
    sns.countplot(x='Year', data=women, palette='mako')
    plt.title('Female Participation Over the Years')
    plt.xticks(rotation=45)
    plt.tight_layout()
    return plt.gcf()

In [ ]:
def gold_over_50():
    gold = merged[(merged['Medal'] == 'Gold') & (merged['Age'] > 50)]
    plt.figure(figsize=(10, 6))
    sns.countplot(y='Sport', data=gold, palette='coolwarm')
    plt.title('Gold Medals by Athletes Aged Over 50')
    plt.tight_layout()
    return plt.gcf()

In [ ]:
def male_weightlifters():
    men = merged[(merged['Sex'] == 'M') & (merged['Season'] == 'Summer')]
    wl = men[men['Sport'] == 'Weightlifting']
    plt.figure(figsize=(12, 6))
    sns.pointplot(x='Year', y='Weight', data=wl, palette='Set2')
    plt.title('Male Weightlifters - Weight Over Years')
    plt.xticks(rotation=45)
    plt.tight_layout()
    return plt.gcf()

In [ ]:
# Unified function to return plots based on selection
def display_plot(option):
    if option == "Gold Medal Age Distribution":
        return gold_medal_age_distribution()
    elif option == "Female Participation Over Years":
        return female_participation()
    elif option == "Gold Medals by Athletes Over 50":
        return gold_over_50()
    elif option == "Weight Trends in Male Weightlifting":
        return male_weightlifters()

# Gradio interface with dropdown
gr.Interface(
    fn=display_plot,
    inputs=gr.Dropdown(
        choices=[
            "Gold Medal Age Distribution",
            "Female Participation Over Years",
            "Gold Medals by Athletes Over 50",
            "Weight Trends in Male Weightlifting"
        ],
        label="Select Visualization"
    ),
    outputs="plot",
    title="üèÖ Olympic Data Analysis Dashboard",
    description="Explore trends, medals, and athlete data from the Olympics dataset."
).launch(share=True)

Colab notebook detected. To show errors in colab notebook, set debug=True in launch()
* Running on public URL: https://d81674a3a443a501a3.gradio.live

This share link expires in 1 week. For free permanent hosting and GPU upgrades, run `gradio deploy` from the terminal in the working directory to deploy to Hugging Face Spaces (https://huggingface.co/spaces)